apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bookmydoc 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookmydoc 
    spec:
      containers:
        - name: bookmydoc 
          image: ctllumak8sacr.azurecr.io/bookmydoc 
          ports:
          - containerPort: 8080